chesspulse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      port: 5432
      dbname: chesspulse
      user: chesspulse
      password: ***RETIRE-DE-L-HISTORIQUE***
      schema: public
      threads: 4