x-airflow-common: &airflow-common
  build: .
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://chesspulse:chesspulse@postgres/airflow_meta
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: 'true'
    PYTHONPATH: /opt/airflow
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./ingestion:/opt/airflow/ingestion
    - ./.env.docker:/opt/airflow/.env
    - airflow_logs:/opt/airflow/logs
    - ./dbt:/opt/airflow/dbt
  depends_on:
    - postgres
  networks:
    - chesspulse_network

services:

  postgres:
    image: postgres:15
    container_name: chesspulse_postgres
    environment:
      POSTGRES_USER: chesspulse
      POSTGRES_PASSWORD: chesspulse
      POSTGRES_DB: chesspulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - chesspulse_network
    restart: unless-stopped

  airflow-webserver:
    <<: *airflow-common
    container_name: chesspulse_airflow_web
    command: webserver
    ports:
      - "8080:8080"
    restart: unless-stopped

  airflow-scheduler:
    <<: *airflow-common
    container_name: chesspulse_airflow_scheduler
    command: scheduler
    restart: unless-stopped

  airflow-init:
    <<: *airflow-common
    container_name: chesspulse_airflow_init
    command: >
      bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@chesspulse.com"
    restart: on-failure

  pipeline-api:
    build:
      context: ./pipeline_api
      dockerfile: Dockerfile
    container_name: chesspulse_pipeline_api
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - postgres
    networks:
      - chesspulse_network
    restart: unless-stopped

volumes:
  postgres_data:
  airflow_logs:

networks:
  chesspulse_network:
    driver: bridge