version: '3.8'

services:

  # Base de données PostgreSQL
  postgres:
    image: postgres:15
    container_name: chesspulse_postgres
    environment:
      POSTGRES_USER: chesspulse
      POSTGRES_PASSWORD: chesspulse
      POSTGRES_DB: chesspulse
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: